sudo: required
services:
 - docker


before_install:
 - docker build -t palsonkansakar/docker-react -f Dockerfile.dev .


script:
 - docker run -e CI=true palsonkansakar/docker-react npm run test

after_script:
  - docker images

before_deploy:
  - docker login -u "palsonkansakar" -p "fantasypalson"
deploy:
  provider: script
  script: docker push palsonkansakar/docker-react
  on:
    branch: master
