sudo: required
services:
 - docker


before_install:
 - docker build -t palsonkansakar/docker-react -f Dockerfile.dev .


script:
 - docker run palsonkansakar/docker-react npm run test -- --coverage 
